### ISSUE TITLE
Annotattions doesn't work with landscape mode

### ISSUE THREAD

**Issue by Midren** [rschroll/rmfuse#3]
I really love the project, but unfortunately, annotations are placed incorrectly if the pdf was in landscape mode.

Example:
![image](https://user-images.githubusercontent.com/32875119/107266173-d300c080-6a4d-11eb-92be-d3d0aa63b0a7.png)

**Comment by rschroll** [comment]
Well that's no good at all!  I'm embarrassed to admit I didn't even think to test this bit of it.  The problem is actually in the rmrl library doing the rendering, so I've opened rschroll/rmrl#2 to track it there.  But we'll leave this open in case other people run into the same issue.

From the screenshot, it looks like the annotations are oriented correctly, but offset from the correct location.  Is that right?  Does it look like they're scaled correctly?  (I realize this is hard to tell until we get the offset right.)

**Comment by rschroll** [comment]
I'm having trouble reproducing this issue with my own documents.  Would you be able to share an example document with me that has the problem?  If you prefer, you can email to me at my Github name at Gmail.  If you're willing to share your annotations as well, you could switch RMfuse to `raw` mode, and then send me the zip file that it gives you.  If not, the original PDF would be preferred to the one RMfuse outputs.

**Comment by Midren** [comment]
@rschroll, sent email with raw file from remarkable and with annotations
